language: nodejs
sudo: false
cache:
  directories:
  - "node_modules"
before_script:
- npm run setup
- npm run build
script:
- npm run test-only
deploy:
  - provider: heroku
    app:
      master: coc-frontend
      development: coc-frontend-dev
    skip_cleanup: true
    api_key:
      secure: N+RBHBvM/nkWVISMNro+zCoNaIiwud3FLzK9FYCNrLDpFpjONj2QIvB+CIBZlWyBpiuA2fL+nhJxmz3aaSQGtRt44DO1XEzLgUEur9bQ2AgimZIxrsutaEiR2qczr3bfdqfQX+pqh4RsxP5ViKkng+/RqBvqY8SiIywIcsM26IFpMBlF5AP0DueRLYTt8ggm6Od74V6YQPb/mS8coJ7CkpW2xcgFFNlbpybASj4zL2hqOFYgsUSqtjHcTXtBvwr5WE97qlBAZBJaxJkqA6YtaW6MqCU36JKzZAhlVVBn9B3Mt0U24JKE5ia4hXOXdGj9Ccy2gbklRFFr7QRDHDTmwh2T6M69MPk7teCpxw9jx9NPlO8vJMeFLKV6hMzzkpmRncCoqtknby84Uw1O5c5KFHzXxjRC90KtPzzm1amdg2eRF48DucXWtQsZ7WiBI/7ueADQxZ4uO+cLLxesv8atm+k7RdtkrKagStv0T2Jv7W6m0suWOqP3S4SkELlOuHMTXSwjko04ODAiwVudgli4d2Y5/54+/hUJvfSrGLeTRKlrnujcvP06rUdpHbKzGBk1IhxBAPwDEstURJCi7v6gjHqmfpQX0TpP4BvMYrz9DLlBpsnT1JfhMRpAD1V0GIovpxBrnleDwmU+z4asw6N+Y+ExLlwwz1plhsQ5eOrVLk4=
